<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Space X  Falcon 9 First Stage Landing Prediction**

## Web scraping Falcon 9 and Falcon Heavy Launches Records from Wikipedia

Estimated time needed: **40** minutes

In this lab, you will be performing web scraping to collect Falcon 9 historical launch records from a Wikipedia page titled `List of Falcon 9 and Falcon Heavy launches`

[https://en.wikipedia.org/wiki/List_of_Falcon\_9\_and_Falcon_Heavy_launches](https://en.wikipedia.org/wiki/List_of_Falcon\_9\_and_Falcon_Heavy_launches?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01)

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module\_1\_L2/images/Falcon9\_rocket_family.svg)

Falcon 9 first stage will land successfully

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/landing\_1.gif)

Several examples of an unsuccessful landing are shown here:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/crash.gif)

More specifically, the launch records are stored in a HTML table shown below:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module\_1\_L2/images/falcon9-launches-wiki.png)

## Objectives

Web scrap Falcon 9 launch records with `BeautifulSoup`:

*   Extract a Falcon 9 launch records HTML table from Wikipedia
*   Parse the table and convert it into a Pandas data frame

First let's import required packages for this lab

In [ ]:
!pip3 install beautifulsoup4
!pip3 install requests

In [4]:
import sys

import requests
from bs4 import BeautifulSoup
import re
import unicodedata
import pandas as pd

and we will provide some helper functions for you to process web scraped HTML table

In [5]:
def date_time(table_cells):
    """
    This function returns the data\e and time from the HTML  table cell
    Input: the  element of a table data cell extracts extra row
    """
    return [data_time.strip() for data_time in list(table_cells.strings)][0:2]

def booster_version(table_cells):
    """
    This function returns the booster version from the HTML  table cell 
    Input: the  element of a table data cell extracts extra row
    """
    out=''.join([booster_version for i,booster_version in enumerate( table_cells.strings) if i%2==0][0:-1])
    return out

def landing_status(table_cells):
    """
    This function returns the landing status from the HTML table cell 
    Input: the  element of a table data cell extracts extra row
    """
    out=[i for i in table_cells.strings][0]
    return out


def get_mass(table_cells):
    mass=unicodedata.normalize("NFKD", table_cells.text).strip()
    if mass:
        mass.find("kg")
        new_mass=mass[0:mass.find("kg")+2]
    else:
        new_mass=0
    return new_mass


def extract_column_from_header(row):
    """
    This function returns the landing status from the HTML table cell 
    Input: the  element of a table data cell extracts extra row
    """
    if (row.br):
        row.br.extract()
    if row.a:
        row.a.extract()
    if row.sup:
        row.sup.extract()
        
    colunm_name = ' '.join(row.contents)
    
    # Filter the digit and empty names
    if not(colunm_name.strip().isdigit()):
        colunm_name = colunm_name.strip()
        return colunm_name

To keep the lab tasks consistent, you will be asked to scrape the data from a snapshot of the  `List of Falcon 9 and Falcon Heavy launches` Wikipage updated on
`9th June 2021`

In [6]:
static_url = "https://en.wikipedia.org/w/index.php?title=List_of_Falcon_9_and_Falcon_Heavy_launches&oldid=1027686922"

Next, request the HTML page from the above URL and get a `response` object

### TASK 1: Request the Falcon9 Launch Wiki page from its URL

First, let's perform an HTTP GET method to request the Falcon9 Launch HTML page, as an HTTP response.

In [8]:
# use requests.get() method with the provided static_url
# assign the response to a object
response = requests.get(static_url)

In [13]:
response.headers

{'date': 'Sun, 09 Apr 2023 15:11:11 GMT', 'server': 'mw1429.eqiad.wmnet', 'x-content-type-options': 'nosniff', 'content-language': 'en', 'vary': 'Accept-Encoding,Cookie,Authorization', 'last-modified': 'Sun, 09 Apr 2023 08:42:07 GMT', 'content-type': 'text/html; charset=UTF-8', 'content-encoding': 'gzip', 'age': '489', 'x-cache': 'cp6011 hit, cp6016 miss', 'x-cache-status': 'hit-local', 'server-timing': 'cache;desc="hit-local", host;desc="cp6016"', 'strict-transport-security': 'max-age=106384710; includeSubDomains; preload', 'report-to': '{ "group": "wm_nel", "max_age": 604800, "endpoints": [{ "url": "https://intake-logging.wikimedia.org/v1/events?stream=w3c.reportingapi.network_error&schema_uri=/w3c/reportingapi/network_error/1.0.0" }] }', 'nel': '{ "report_to": "wm_nel", "max_age": 604800, "failure_fraction": 0.05, "success_fraction": 0.0}', 'set-cookie': 'WMF-Last-Access=09-Apr-2023;Path=/;HttpOnly;secure;Expires=Thu, 11 May 2023 12:00:00 GMT, WMF-Last-Access-Global=09-Apr-2023;Path=/;Domain=.wikipedia.org;HttpOnly;secure;Expires=Thu, 11 May 2023 12:00:00 GMT, WMF-DP=04f;Path=/;HttpOnly;secure;Expires=Mon, 10 Apr 2023 00:00:00 GMT, GeoIP=NG:LA:Lagos:6.45:3.39:v4; Path=/; secure; Domain=.wikipedia.org', 'x-client-ip': '102.89.47.49', 'cache-control': 'private, s-maxage=0, max-age=0, must-revalidate', 'accept-ranges': 'bytes', 'transfer-encoding': 'chunked'}

Create a `BeautifulSoup` object from the HTML `response`

In [15]:
# Use BeautifulSoup() to create a BeautifulSoup object from a response text content
soup = BeautifulSoup(response.text, 'html.parser')

Print the page title to verify if the `BeautifulSoup` object was created properly

In [18]:
# Use soup.title attribute
type(soup.title)
soup.h3

### TASK 2: Extract all column/variable names from the HTML table header

Next, we want to collect all relevant column names from the HTML table header

Let's try to find all tables on the wiki page first. If you need to refresh your memory about `BeautifulSoup`, please check the external reference link towards the end of this lab

In [29]:
# Use the find_all function in the BeautifulSoup object, with element type `table`
# Assign the result to a list called `html_tables`
html_tables = soup.find_all('table')

Starting from the third table is our target table contains the actual launch records.

In [31]:
# Let's print the third table and check its content
first_launch_table = html_tables[2]
print(first_launch_table)

You should able to see the columns names embedded in the table header elements `<th>` as follows:

```
<tr>
<th scope="col">Flight No.
</th>
<th scope="col">Date and<br/>time (<a href="/wiki/Coordinated_Universal_Time" title="Coordinated Universal Time">UTC</a>)
</th>
<th scope="col"><a href="/wiki/List_of_Falcon_9_first-stage_boosters" title="List of Falcon 9 first-stage boosters">Version,<br/>Booster</a> <sup class="reference" id="cite_ref-booster_11-0"><a href="#cite_note-booster-11">[b]</a></sup>
</th>
<th scope="col">Launch site
</th>
<th scope="col">Payload<sup class="reference" id="cite_ref-Dragon_12-0"><a href="#cite_note-Dragon-12">[c]</a></sup>
</th>
<th scope="col">Payload mass
</th>
<th scope="col">Orbit
</th>
<th scope="col">Customer
</th>
<th scope="col">Launch<br/>outcome
</th>
<th scope="col"><a href="/wiki/Falcon_9_first-stage_landing_tests" title="Falcon 9 first-stage landing tests">Booster<br/>landing</a>
</th></tr>
```

Next, we just need to iterate through the `<th>` elements and apply the provided `extract_column_from_header()` to extract column name one by one

In [33]:
column_names = []

# Apply find_all() function with `th` element on first_launch_table
# Iterate each th element and apply the provided extract_column_from_header() to get a column name
# Append the Non-empty column name (`if name is not None and len(name) > 0`) into a list called column_names

tables = first_launch_table.find_all('th')
for table in tables:
    name = extract_column_from_header(table)
    if name is not None and len(name) > 0:
        column_names.append(name)

Check the extracted column names

In [34]:
print(column_names)

['Flight No.', 'Date and time ( )', 'Launch site', 'Payload', 'Payload mass', 'Orbit', 'Customer', 'Launch outcome']

## TASK 3: Create a data frame by parsing the launch HTML tables

We will create an empty dictionary with keys from the extracted column names in the previous task. Later, this dictionary will be converted into a Pandas dataframe

In [77]:
launch_dict= dict.fromkeys(column_names)

# Remove an irrelvant column
del launch_dict['Date and time ( )']

# Let's initial the launch_dict with each value to be an empty list
launch_dict['Flight No.'] = []
launch_dict['Launch site'] = []
launch_dict['Payload'] = []
launch_dict['Payload mass'] = []
launch_dict['Orbit'] = []
launch_dict['Customer'] = []
launch_dict['Launch outcome'] = []
# Added some new columns
launch_dict['Version Booster']=[]
launch_dict['Booster landing']=[]
launch_dict['Date']=[]
launch_dict['Time']=[]

Next, we just need to fill up the `launch_dict` with launch records extracted from table rows.

Usually, HTML tables in Wiki pages are likely to contain unexpected annotations and other types of noises, such as reference links `B0004.1[8]`, missing values `N/A [e]`, inconsistent formatting, etc.

To simplify the parsing process, we have provided an incomplete code snippet below to help you to fill up the `launch_dict`. Please complete the following code snippet with TODOs or you can choose to write your own logic to parse all launch tables:

In [78]:
extracted_row = 0
#Extract each table 
for table_number,table in enumerate(soup.find_all('table',"wikitable plainrowheaders collapsible")):
   # get table row 
    for rows in table.find_all("tr"):
        #check to see if first table heading is as number corresponding to launch a number 
        if rows.th:
            if rows.th.string:
                flight_number=rows.th.string.strip()
                flag=flight_number.isdigit()
        else:
            flag=False
        #get table element 
        row=rows.find_all('td')
        #if it is number save cells in a dictonary 
        if flag:
            extracted_row += 1
            # Flight Number value
            # TODO: Append the flight_number into launch_dict with key `Flight No.`
            #print(flight_number)
            print(f'The Flight No is {flight_number} \n')
            launch_dict['Flight No.'].append(flight_number)
            
            datatimelist=date_time(row[0])
            
            # Date value
            # TODO: Append the date into launch_dict with key `Date`
             #print(date)
            date = datatimelist[0].strip(',')
            print(f'The date is {date} \n')
            launch_dict['Date'].append(date)
            
            # Time value
            # TODO: Append the time into launch_dict with key `Time`
            time = datatimelist[1]
            #print(time)
            print(f'The time is {time} \n')
            launch_dict['Time'].append(time)
              
            # Booster version
            # TODO: Append the bv into launch_dict with key `Version Booster`
            bv=booster_version(row[1])
            if not(bv):
                bv=row[1].a.string
            print(bv)
            launch_dict['Version Booster'].append(bv)
            
            # Launch Site
            # TODO: Append the bv into launch_dict with key `Launch Site`
            launch_site = row[2].a.string
            launch_dict['Launch site'].append(launch_site)
            #print(launch_site)
            
            # Payload
            # TODO: Append the payload into launch_dict with key `Payload`
            payload = row[3].a.string
            #print(payload)
            launch_dict['Payload'].append(payload)
            
            # Payload Mass
            # TODO: Append the payload_mass into launch_dict with key `Payload mass`
            payload_mass = get_mass(row[4])
            #print(payload)
            launch_dict['Payload mass'].append(payload_mass)
            # Orbit
            # TODO: Append the orbit into launch_dict with key `Orbit`
            orbit = row[5].a.string
            #print(orbit)
            launch_dict['Orbit'].append(orbit)
            # Customer
            # TODO: Append the customer into launch_dict with key `Customer`
            try:
                customer = row[6].a.string
                #print(customer)
                launch_dict['Customer'].append(customer)
            except AttributeError:
                launch_dict['Customer'].append(None)
            
            # Launch outcome
            # TODO: Append the launch_outcome into launch_dict with key `Launch outcome`
            launch_outcome = list(row[7].strings)[0]
            #print(launch_outcome)
            launch_dict['Launch outcome'].append(launch_outcome)
            # Booster landing
            # TODO: Append the launch_outcome into launch_dict with key `Booster landing`
            booster_landing = landing_status(row[8])
            #print(booster_landing)
            launch_dict['Booster landing'].append(booster_landing)

The Flight No is 1

The date is 4 June 2010

The time is 18:45

F9 v1.0B0003.1
The Flight No is 2

The date is 8 December 2010

The time is 15:43

F9 v1.0B0004.1
The Flight No is 3

The date is 22 May 2012

The time is 07:44

F9 v1.0B0005.1
The Flight No is 4

The date is 8 October 2012

The time is 00:35

F9 v1.0B0006.1
The Flight No is 5

The date is 1 March 2013

The time is 15:10

F9 v1.0B0007.1
The Flight No is 6

The date is 29 September 2013

The time is 16:00

F9 v1.1B1003
The Flight No is 7

The date is 3 December 2013

The time is 22:41

F9 v1.1
The Flight No is 8

The date is 6 January 2014

The time is 22:06

F9 v1.1
The Flight No is 9

The date is 18 April 2014

The time is 19:25

F9 v1.1
The Flight No is 10

The date is 14 July 2014

The time is 15:15

F9 v1.1
The Flight No is 11

The date is 5 August 2014

The time is 08:00

F9 v1.1
The Flight No is 12

The date is 7 September 2014

The time is 05:00

F9 v1.1
The Flight No is 13

The date is 21 September 2014

The time is 05:52

F9 v1.1
The Flight No is 14

The date is 10 January 2015

The time is 09:47

F9 v1.1
The Flight No is 15

The date is 11 February 2015

The time is 23:03

F9 v1.1
The Flight No is 16

The date is 2 March 2015

The time is 03:50

F9 v1.1
The Flight No is 17

The date is 14 April 2015

The time is 20:10

F9 v1.1
The Flight No is 18

The date is 27 April 2015

The time is 23:03

F9 v1.1
The Flight No is 19

The date is 28 June 2015

The time is 14:21

F9 v1.1
The Flight No is 20

The date is 22 December 2015

The time is 01:29

F9 FT
The Flight No is 21

The date is 17 January 2016

The time is 18:42

F9 v1.1
The Flight No is 22

The date is 4 March 2016

The time is 23:35

F9 FT
The Flight No is 23

The date is 8 April 2016

The time is 20:43

F9 FT
The Flight No is 24

The date is 6 May 2016

The time is 05:21

F9 FT
The Flight No is 25

The date is 27 May 2016

The time is 21:39

F9 FT
The Flight No is 26

The date is 15 June 2016

The time is 14:29

F9 FT
The Flight No is 27

The date is 18 July 2016

The time is 04:45

F9 FT
The Flight No is 28

The date is 14 August 2016

The time is 05:26

F9 FT
The Flight No is 29

The date is 14 January 2017

The time is 17:54

F9 FT
The Flight No is 30

The date is 19 February 2017

The time is 14:39

F9 FT
The Flight No is 31

The date is 16 March 2017

The time is 06:00

F9 FT
The Flight No is 32

The date is 30 March 2017

The time is 22:27

F9 FT♺
The Flight No is 33

The date is 1 May 2017

The time is 11:15

F9 FT
The Flight No is 34

The date is 15 May 2017

The time is 23:21

F9 FT
The Flight No is 35

The date is 3 June 2017

The time is 21:07

F9 FT
The Flight No is 36

The date is 23 June 2017

The time is 19:10

F9 FTB1029.2
The Flight No is 37

The date is 25 June 2017

The time is 20:25

F9 FT
The Flight No is 38

The date is 5 July 2017

The time is 23:38

F9 FT
The Flight No is 39

The date is 14 August 2017

The time is 16:31

F9 B4
The Flight No is 40

The date is 24 August 2017

The time is 18:51

F9 FT
The Flight No is 41

The date is 7 September 2017

The time is 14:00

F9 B4
The Flight No is 42

The date is 9 October 2017

The time is 12:37

F9 B4
The Flight No is 43

The date is 11 October 2017

The time is 22:53:00

F9 FTB1031.2
The Flight No is 44

The date is 30 October 2017

The time is 19:34

F9 B4
The Flight No is 45

The date is 15 December 2017

The time is 15:36

F9 FTB1035.2
The Flight No is 46

The date is 23 December 2017

The time is 01:27

F9 FTB1036.2
The Flight No is 47

The date is 8 January 2018

The time is 01:00

F9 B4
The Flight No is 48

The date is 31 January 2018

The time is 21:25

F9 FTB1032.2
The Flight No is 49

The date is 22 February 2018

The time is 14:17

F9 FTB1038.2
The Flight No is 50

The date is 6 March 2018

The time is 05:33

F9 B4
The Flight No is 51

The date is 30 March 2018

The time is 14:14

F9 B4B1041.2
The Flight No is 52

The date is 2 April 2018

The time is 20:30

F9 B4B1039.2
The Flight No is 53

The date is 18 April 2018

The time is 22:51

F9 B4
The Flight No is 54

The date is 11 May 2018

The time is 20:14

F9 B5B1046.1
The Flight No is 55

The date is 22 May 2018

The time is 19:47

F9 B4B1043.2
The Flight No is 56

The date is 4 June 2018

The time is 04:45

F9 B4B1040.2
The Flight No is 57

The date is 29 June 2018

The time is 09:42

F9 B4B1045.2
The Flight No is 58

The date is 22 July 2018

The time is 05:50

F9 B5
The Flight No is 59

The date is 25 July 2018

The time is 11:39

F9 B5B1048
The Flight No is 60

The date is 7 August 2018

The time is 05:18

F9 B5B1046.2
The Flight No is 61

The date is 10 September 2018

The time is 04:45

F9 B5
The Flight No is 62

The date is 8 October 2018

The time is 02:22

F9 B5B1048.2
The Flight No is 63

The date is 15 November 2018

The time is 20:46

F9 B5B1047.2
The Flight No is 64

The date is 3 December 2018

The time is 18:34:05

F9 B5B1046.3
The Flight No is 65

The date is 5 December 2018

The time is 18:16

F9 B5
The Flight No is 66

The date is 23 December 2018

The time is 13:51

F9 B5
The Flight No is 67

The date is 11 January 2019

The time is 15:31

F9 B5B1049.2
The Flight No is 68

The date is 22 February 2019

The time is 01:45

F9 B5B1048.3
The Flight No is 69

The date is 2 March 2019

The time is 07:49

F9 B5[268]
The Flight No is 70

The date is 4 May 2019

The time is 06:48

F9 B5
The Flight No is 71

The date is 24 May 2019

The time is 02:30

F9 B5B1049.3
The Flight No is 72

The date is 12 June 2019

The time is 14:17

F9 B5B1051.2
The Flight No is 73

The date is 25 July 2019

The time is 22:01

F9 B5B1056.2
The Flight No is 74

The date is 6 August 2019

The time is 23:23

F9 B5B1047.3
The Flight No is 75

The date is 11 November 2019

The time is 14:56

F9 B5
The Flight No is 76

The date is 5 December 2019

The time is 17:29

F9 B5
The Flight No is 77

The date is 17 December 2019

The time is 00:10

F9 B5B1056.3
The Flight No is 78

The date is 7 January 2020

The time is 02:19:21

F9 B5
The Flight No is 79

The date is 19 January 2020

The time is 15:30

F9 B5
The Flight No is 80

The date is 29 January 2020

The time is 14:07

F9 B5
The Flight No is 81

The date is 17 February 2020

The time is 15:05

F9 B5
The Flight No is 82

The date is 7 March 2020

The time is 04:50

F9 B5
The Flight No is 83

The date is 18 March 2020

The time is 12:16

F9 B5
The Flight No is 84

The date is 22 April 2020

The time is 19:30

F9 B5
The Flight No is 85

The date is 30 May 2020

The time is 19:22

F9 B5
The Flight No is 86

The date is 4 June 2020

The time is 01:25

F9 B5
The Flight No is 87

The date is 13 June 2020

The time is 09:21

F9 B5
The Flight No is 88

The date is 30 June 2020

The time is 20:10:46

F9 B5
The Flight No is 89

The date is 20 July 2020

The time is 21:30

F9 B5B1058.2
The Flight No is 90

The date is 7 August 2020

The time is 05:12

F9 B5
The Flight No is 91

The date is 18 August 2020

The time is 14:31

F9 B5B1049.6
The Flight No is 92

The date is 30 August 2020

The time is 23:18

F9 B5
The Flight No is 93

The date is 3 September 2020

The time is 12:46:14

F9 B5B1060.2
The Flight No is 94

The date is 6 October 2020

The time is 11:29:34

F9 B5B1058.3
The Flight No is 95

The date is 18 October 2020

The time is 12:25:57

F9 B5B1051.6
The Flight No is 96

The date is 24 October 2020

The time is 15:31:34

F9 B5
The Flight No is 97

The date is 5 November 2020

The time is 23:24:23

F9 B5
The Flight No is 98

The date is 16 November 2020

The time is 00:27

F9 B5
The Flight No is 99

The date is 21 November 2020

The time is 17:17:08

F9 B5
The Flight No is 100

The date is 25 November 2020

The time is 02:13

F9 B5 ♺
The Flight No is 101

The date is 6 December 2020

The time is 16:17:08

F9 B5 ♺
The Flight No is 102

The date is 13 December 2020

The time is 17:30:00

F9 B5 ♺
The Flight No is 103

The date is 19 December 2020

The time is 14:00:00

F9 B5 ♺
The Flight No is 104

The date is 8 January 2021

The time is 02:15

F9 B5
The Flight No is 105

The date is 20 January 2021

The time is 13:02

F9 B5B1051.8
The Flight No is 106

The date is 24 January 2021

The time is 15:00

F9 B5B1058.5
The Flight No is 107

The date is 4 February 2021

The time is 06:19

F9 B5 ♺
The Flight No is 108

The date is 16 February 2021

The time is 03:59:37

F9 B5 ♺
The Flight No is 109

The date is 4 March 2021

The time is 08:24

F9 B5 ♺
The Flight No is 110

The date is 11 March 2021

The time is 08:13:29

F9 B5 ♺
The Flight No is 111

The date is 14 March 2021

The time is 10:01

F9 B5 ♺
The Flight No is 112

The date is 24 March 2021

The time is 08:28

F9 B5B1060.6
The Flight No is 113

The date is 7 April 2021

The time is 16:34

F9 B5 ♺
The Flight No is 114

The date is 23 April 2021

The time is 9:49

F9 B5B1061.2
The Flight No is 115

The date is 29 April 2021

The time is 03:44

F9 B5B1060.7
The Flight No is 116

The date is 4 May 2021

The time is 19:01

F9 B5B1049.9
The Flight No is 117

The date is 9 May 2021

The time is 06:42

F9 B5B1051.10
The Flight No is 118

The date is 15 May 2021

The time is 22:56

F9 B5B1058.8
The Flight No is 119

The date is 26 May 2021

The time is 18:59

F9 B5B1063.2
The Flight No is 120

The date is 3 June 2021

The time is 17:29

F9 B5B1067.1
The Flight No is 121

The date is 6 June 2021

The time is 04:26

F9 B5

In [81]:
len(launch_dict['Flight No.'])#[100:]

121

After you have fill in the parsed launch record values into `launch_dict`, you can create a dataframe from it.

In [83]:
df=pd.DataFrame(launch_dict)
df.head()

,Flight No.,Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Version Booster,Booster landing,Date,Time
0,1,CCAFS,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success\n,F9 v1.0B0003.1,Failure,4 June 2010,18:45
1,2,CCAFS,Dragon,0,LEO,NASA,Success,F9 v1.0B0004.1,Failure,8 December 2010,15:43
2,3,CCAFS,Dragon,525 kg,LEO,NASA,Success,F9 v1.0B0005.1,No attempt\n,22 May 2012,07:44
3,4,CCAFS,SpaceX CRS-1,"4,700 kg",LEO,NASA,Success\n,F9 v1.0B0006.1,No attempt,8 October 2012,00:35
4,5,CCAFS,SpaceX CRS-2,"4,877 kg",LEO,NASA,Success\n,F9 v1.0B0007.1,No attempt\n,1 March 2013,15:10

We can now export it to a <b>CSV</b> for the next section, but to make the answers consistent and in case you have difficulties finishing this lab.

Following labs will be using a provided dataset to make each lab independent.

In [84]:
df.to_csv('spacex_web_scraped.csv', index=False)

## Authors

<a href="https://www.linkedin.com/in/yan-luo-96288783/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">Yan Luo</a>

<a href="https://www.linkedin.com/in/nayefaboutayoun/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">Nayef Abou Tayoun</a>

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description          |
| ----------------- | ------- | ---------- | --------------------------- |
| 2021-06-09        | 1.0     | Yan Luo    | Tasks updates               |
| 2020-11-10        | 1.0     | Nayef      | Created the initial version |

Copyright © 2021 IBM Corporation. All rights reserved.